version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - gochecknoinits
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
    # staticcheck:
    #   checks:
    #     - all
    #     - -ST1000
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: _test\.go
        linters:
          - govet
        text: fieldalignment

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/PoQuatre/ft_transcendence/backend
      extra:
        balance-calls: true
        clothe-returns: true
        group-params: true
    goimports:
      local-prefixes:
        - github.com/PoQuatre/ft_transcendence/backend
