local all postgres trust

hostssl all vault_admin 0.0.0.0/0 scram-sha-256
hostssl all vault_admin ::/0 scram-sha-256

hostssl all +app_readonly,+app_readwrite,+app_migrate,+app_admin 0.0.0.0/0 scram-sha-256
hostssl all +app_readonly,+app_readwrite,+app_migrate,+app_admin ::/0 scram-sha-256

hostssl all postgres 0.0.0.0/0 reject
hostssl all postgres ::/0 reject
